### ISSUE TITLE
error when using bsvs 57

### ISSUE THREAD

**Issue by WhundAlt** [athlondevv/BS-V57#2]
```

    ____                      __   _____ __
   / __ )_________ __      __/ /  / ___// /_____ ___________
  / __  / ___/ __ `/ | /| / / /   \__ \/ __/ __ `/ ___/ ___/
 / /_/ / /  / /_/ /| |/ |/ / /   ___/ / /_/ /_/ / /  (__  )
/_____/_/   \__,_/ |__/|__/_/   /____/\__/\__,_/_/  /____/


Listening for new connection...
New connection with address 192.168.1.14 on port 60900
10101 : LoginMessage created
[WARNING] Too long String encountered, length 4294967295, max 900000
[WARNING] Negative readBytes length encountered.
Traceback (most recent call last):
  File "C:\Users\ASUS\Downloads\bsvs-v57 (1)\Classes\MessageManager.py", line 16, in receiveMessage
    message.fields = message.decode()
  File "C:\Users\ASUS\Downloads\bsvs-v57 (1)\Classes\Packets\Client\Authentification\LoginMessage.py", line 49, in decode
    fields["SupercellIdToken"] = self.readCompressedString()
  File "C:\Users\ASUS\Downloads\bsvs-v57 (1)\Classes\ByteStream.py", line 578, in readCompressedString
    return zlib.decompress(self.readBytes(data_length - 4))
zlib.error: Error -5 while decompressing data: incomplete or truncated stream

23457 : LobbyInfoMessage created
```

any idea why?

**Comment by usernamename01** [comment]
just use contentupdater.zip archive inside bsvs57

ill redownload working one later

**Comment by usernamename01** [comment]
corrected

**Comment by WhundAlt** [comment]
yet another issue, the readme says that you can change the port in the apk, yet theres no port changer in the apk

**Comment by usernamename01** [comment]
i just copied text from crazor git
so if u need to change port - look for script with port

**Comment by WhundAlt** [comment]
just a reminder that theres now a v58 server by soufgameyt (idk if theres a client tho)

**Comment by usernamename01** [comment]
i completely forgot, ill go and upload it (i forgot about my github too)
